#canvas.before:
#    Color:
#        rgba: .5, .5, .5, 1
#    Line:
#        width: 2
#        rectangle: self.x, self.y, self.width, self.height

<CustomLabel@Label>
    font_size: 28

<Plot>:
	LineGraph:
		background_normal: ''
        background_color: [0,0,0,1]
        bg_color: ['Grey','000']
		orientation: 'vertical'
		padding: '5dp'
		spacing: '5dp'
		mode: "Line"
		id: line_graph

<GUILayout>
    ScreenManager:
        id: manager

        Screen:
            name:"settings_screen"
            GestureBox:
                on_top_to_bottom_line: manager.current = '1st_floor_center_screen'; manager.transition.direction = 'down'
                orientation: "vertical"

                CustomLabel:
                    text: "Settings"
                    size_hint_y: None
                    height: 40

                BoxLayout:
                    GridLayout:
                        cols: 4
                        rows: 3
                        spacing: 10
                        padding: 10

                        # 1st row
                        AnchorLayout:
                            anchor_x: 'center'
                            Gauge:
                                id: gauge_settings_temperature
                                size_hint_y: 0.33
                                value: root.hw_manager.dht22_0.temperature
                                relative_path: './sensors/temperature_gauge.png'
                        Label:
                            text: "Temperature [in °C]"
                        Slider:
                            id: slider_settings_temperature_adjustment
                            min: 10
                            max: 40
                            value: 20
                            orientation: 'horizontal'
                            on_value: root.hw_manager.manual_temperature_adjustment(self.value)
                        Label:
                            text: "Temperature will be \n set to " + "{:.2f}".format(slider_settings_temperature_adjustment.value) + "°C"

                        # 2nd row
                        AnchorLayout:
                            anchor_x: 'center'
                            Gauge:
                                id: gauge_settings_average_brightness
                                size_hint_y: 0.33
                                value: root.hw_manager.bh1750_1_1.brightness
                                relative_path: './sensors/uv_gauge.png'
                        Label:
                            text: "Average brightness [in nm]"
                        Switch:
                            on_active: root.hw_manager.enable_lights(self.active)
                        Label:
                            text: "Enable lights"

                        AnchorLayout:
                            anchor_x: 'center'
                            Gauge:
                                id: gauge_settings_water_level
                                size_hint_y: 0.33
                                value: 50
                        Label:
                            text: "Water level [in mm]"
                        Switch:
                            on_active: root.hw_manager.enable_automatic_water_filling(self.active)
                        Label:
                            text: "Enable automatic \n water filling"

        Screen:
            name: "1st_floor_center_screen"
            GestureBox:
                on_top_to_bottom_line: manager.current = '2nd_floor_center_screen';  manager.transition.direction = 'down'
                on_bottom_to_top_line: manager.current = 'settings_screen'; manager.transition.direction = 'up'
                on_left_to_right_line: manager.current = '1st_floor_left_screen'; manager.transition.direction = 'right'
                on_right_to_left_line: manager.current = '1st_floor_right_screen'; manager.transition.direction = 'left'
                orientation: "vertical"

                CustomLabel:
                    text: "1st Floor Center"
                    size_hint_y: None
                    height: 40
                TabbedPanel:
                    id: floor1_center_tab_panel
                    do_default_tab: False
                    size_hint: (1,0.8)
                    TabbedPanelItem:
                        id: floor1_center_overview_tab
                        text: "Overview"
                        background_color: (2.09, 1.32, 0, 1) #orange tab

                        GridLayout:
                            cols: 4
                            rows: 3
                            spacing: 10
                            padding: 10

                            CustomLabel:
                                text: "Temperature \n [in °C]"
                            AnchorLayout:
                                anchor_x: 'center'
                                Gauge:
                                    id: gauge_1st_center_overview_temperature
                                    size_hint_y: 0.33
                                    value: root.hw_manager.dht22_0.temperature
                                    relative_path: './sensors/temperature_gauge.png'

                            CustomLabel:
                                text: "Humidity \n [in %]"
                            AnchorLayout:
                                anchor_x: 'center'
                                Gauge:
                                    id: gauge_1st_center_overview_humidity
                                    size_hint_y: 0.33
                                    value: root.hw_manager.dht22_0.humidity

                            CustomLabel:
                                text: "Air Pressure \n [in hPa]"
                            AnchorLayout:
                                anchor_x: 'center'
                                Gauge:
                                    id: gauge_1st_center_overview_air_pressure
                                    size_hint_y: 0.33
                                    value: root.hw_manager.water_1.value
                                    relative_path: './sensors/air_pressure_gauge.png'

                            CustomLabel:
                                text: "UV \n [in nm]"
                            AnchorLayout:
                                anchor_x: 'center'
                                Gauge:
                                    id: gauge_1st_center_overview_uv
                                    size_hint_y: 0.33
                                    value: root.hw_manager.bh1750_1_1.brightness
                                    relative_path: './sensors/uv_gauge.png'

                            CustomLabel:
                                text: "Soil Moisture \n [in %]"
                            AnchorLayout:
                                anchor_x: 'center'
                                Gauge:
                                    id: gauge_1st_center_overview_soil_moisture
                                    size_hint_y: 0.33
                                    value: root.hw_manager.water_2.value

                    TabbedPanelItem:
                        id: floor1_center_temperature_tab
                        text: "Temperature"

                        GridLayout:
                            rows: 2
                            GridLayout:
                                cols: 2
                                size_hint_y: None
                                height: 90

                                AnchorLayout:
                                    anchor_x: 'left'
                                    CustomLabel:
                                        text: "Temperature Value [in °C]"
                                        size_hint_x: None
                                        width : 500

                                AnchorLayout:
                                    anchor_x: 'right'
                                    Gauge:
                                        id: gauge_1st_center_tab_temperature
                                        size_hint_x: None
                                        size_hint_y: 0.5
                                        width: 300
                                        value: root.hw_manager.dht22_0.temperature
                                        relative_path: './sensors/temperature_gauge.png'

                            GridLayout:
                                cols: 2
                                GridLayout:
                                    rows: 2
                                    width: 100
                                    size_hint_x: None
                                    Button:
                                        text: "show \n less"
                                        on_press: plot_1st_center_tab_temperature.showLess()

                                    Button:
                                        text: "show \n more"
                                        on_press: plot_1st_center_tab_temperature.showMore()

                                BoxLayout:
                                    Plot:
                                        id: plot_1st_center_tab_temperature
                                        yMin: -10
                                        yMax: 40
                                        yStep: 10
                                        value: root.hw_manager.dht22_0.temperature
                                        name: "1st_floor_center_screen"
                                        current: manager.current


                    TabbedPanelItem:
                        id: floor1_center_humidity_tab
                        text: "Humidity"

                        GridLayout:
                            rows: 2
                            GridLayout:
                                cols: 2
                                size_hint_y: None
                                height: 90

                                AnchorLayout:
                                    anchor_x: 'left'
                                    CustomLabel:
                                        text: "Humidity Value [in %]"
                                        size_hint_x: None
                                        width : 500

                                AnchorLayout:
                                    anchor_x: 'right'
                                    Gauge:
                                        id: gauge_1st_center_tab_humidity
                                        size_hint_x: None
                                        size_hint_y: 0.5
                                        width: 300
                                        value: root.hw_manager.dht22_0.humidity

                            GridLayout:
                                cols: 2
                                GridLayout:
                                    rows: 2
                                    width: 100
                                    size_hint_x: None
                                    Button:
                                        text: "show \n less"
                                        on_press: plot_1st_center_tab_humidity.showLess()

                                    Button:
                                        text: "show \n more"
                                        on_press: plot_1st_center_tab_humidity.showMore()

                                BoxLayout:
                                    Plot:
                                        id: plot_1st_center_tab_humidity
                                        yMin: 0
                                        yMax: 100
                                        yStep: 10
                                        value: root.hw_manager.dht22_0.humidity
                                        name: "1st_floor_center_screen"
                                        current: manager.current

                    TabbedPanelItem:
                        id: floor1_center_air_pressure_tab
                        text: "Air Pressure"

                        GridLayout:
                            rows: 2
                            GridLayout:
                                cols: 2
                                size_hint_y: None
                                height: 90

                                AnchorLayout:
                                    anchor_x: 'left'
                                    CustomLabel:
                                        text: "Air Pressure Value [in hPa]"
                                        size_hint_x: None
                                        width : 500

                                AnchorLayout:
                                    anchor_x: 'right'
                                    Gauge:
                                        id: gauge_1st_center_tab_air_pressure
                                        size_hint_x: None
                                        size_hint_y: 0.5
                                        width: 300
                                        value: root.hw_manager.water_1.value
                                        relative_path: './sensors/air_pressure_gauge.png'

                            GridLayout:
                                cols: 2
                                GridLayout:
                                    rows: 2
                                    width: 100
                                    size_hint_x: None
                                    Button:
                                        text: "show \n less"
                                        on_press: plot_1st_center_tab_air_pressure.showLess()

                                    Button:
                                        text: "show \n more"
                                        on_press: plot_1st_center_tab_air_pressure.showMore()

                                BoxLayout:
                                    Plot:
                                        id: plot_1st_center_tab_air_pressure
                                        yMin: 950
                                        yMax: 1050
                                        yStep: 10
                                        value: root.hw_manager.water_1.value
                                        name: "1st_floor_center_screen"
                                        current: manager.current

                    TabbedPanelItem:
                        id: floor1_center_uv_tab
                        text: "UV"

                        GridLayout:
                            rows: 2
                            GridLayout:
                                cols: 2
                                size_hint_y: None
                                height: 90

                                AnchorLayout:
                                    anchor_x: 'left'
                                    CustomLabel:
                                        text: "UV Value [in nm]"
                                        size_hint_x: None
                                        width : 500

                                AnchorLayout:
                                    anchor_x: 'right'
                                    Gauge:
                                        id: gauge_1st_center_tab_uv
                                        size_hint_x: None
                                        size_hint_y: 0.5
                                        width: 300
                                        value: root.hw_manager.bh1750_1_1.brightness
                                        relative_path: './sensors/uv_gauge.png'

                            GridLayout:
                                cols: 2
                                GridLayout:
                                    rows: 2
                                    width: 100
                                    size_hint_x: None
                                    Button:
                                        text: "show \n less"
                                        on_press: plot_1st_center_tab_uv.showLess()

                                    Button:
                                        text: "show \n more"
                                        on_press: plot_1st_center_tab_uv.showMore()

                                BoxLayout:
                                    Plot:
                                        id: plot_1st_center_tab_uv
                                        yMin: 100
                                        yMax: 400
                                        yStep: 50
                                        value: root.hw_manager.bh1750_1_1.brightness
                                        name: "1st_floor_center_screen"
                                        current: manager.current

                    TabbedPanelItem:
                        id: floor1_center_soil_moisture_tab
                        text: "Soil Moisture"

                        GridLayout:
                            rows: 2
                            GridLayout:
                                cols: 2
                                size_hint_y: None
                                height: 90

                                AnchorLayout:
                                    anchor_x: 'left'
                                    CustomLabel:
                                        text: "Soil Moisture Value [in %]"
                                        size_hint_x: None
                                        width : 500

                                AnchorLayout:
                                    anchor_x: 'right'
                                    Gauge:
                                        id: gauge_1st_center_tab_soil_moisture
                                        size_hint_x: None
                                        size_hint_y: 0.5
                                        width: 300
                                        value: root.hw_manager.water_2.value

                            GridLayout:
                                cols: 2
                                GridLayout:
                                    rows: 2
                                    width: 100
                                    size_hint_x: None
                                    Button:
                                        text: "show \n less"
                                        on_press: plot_1st_center_tab_soil_moisture.showLess()

                                    Button:
                                        text: "show \n more"
                                        on_press: plot_1st_center_tab_soil_moisture.showMore()

                                BoxLayout:
                                    Plot:
                                        id: plot_1st_center_tab_soil_moisture
                                        yMin: 0
                                        yMax: 100
                                        yStep: 10
                                        value: root.hw_manager.water_2.value
                                        name: "1st_floor_center_screen"
                                        current: manager.current

        Screen:
            name: "1st_floor_left_screen"
            GestureBox:
                on_bottom_to_top_line: manager.current = 'settings_screen';  manager.transition.direction = 'up'
                on_right_to_left_line: manager.current = '1st_floor_center_screen';  manager.transition.direction = 'left'
                on_top_to_bottom_line: manager.current = '2nd_floor_center_screen';  manager.transition.direction = 'down'
                orientation: "vertical"

                CustomLabel:
					text: "1st Floor Left"
					size_hint: (1,0.05)
                TabbedPanel:
                    size_hint: (1,0.8)
                    id: floor1_left_tab_panel
                    do_default_tab: False
                    TabbedPanelItem:
                        id: floor1_left_1st_tab
                        text: "1st tab"
                        CustomLabel:
                            text: "1st tab"
                    TabbedPanelItem:
                        id: floor1_left_2nd_tab
                        text: "2nd tab"
                        CustomLabel:
                            text: "2nd tab"

        Screen:
            name: "1st_floor_right_screen"
            GestureBox:
                on_bottom_to_top_line: manager.current = 'settings_screen';  manager.transition.direction = 'up'
                on_left_to_right_line: manager.current = '1st_floor_center_screen';  manager.transition.direction = 'right'
                on_top_to_bottom_line: manager.current = '2nd_floor_center_screen';  manager.transition.direction = 'down'
                orientation: "vertical"

                CustomLabel:
					text: "1st Floor Right"
					size_hint: (1,0.05)
                TabbedPanel:
                    size_hint: (1,0.8)
                    id: floor1_right_tab_panel
                    do_default_tab: False
                    TabbedPanelItem:
                        id: floor1_right_1st_tab
                        text: "1st tab"
                        CustomLabel:
                            text: "1st tab"
                    TabbedPanelItem:
                        id: floor1_right_2nd_tab
                        text: "2nd tab"
                        CustomLabel:
                            text: "2nd tab"

        Screen:
            name: "2nd_floor_center_screen"
            GestureBox:
                on_bottom_to_top_line: manager.current = '1st_floor_center_screen';  manager.transition.direction = 'up'
                on_left_to_right_line: manager.current = '2nd_floor_left_screen'; manager.transition.direction = 'right'
                on_right_to_left_line: manager.current = '2nd_floor_right_screen'; manager.transition.direction = 'left'
                orientation: "vertical"

                CustomLabel:
					text: "2nd Floor Center"
					size_hint: (1,0.05)
                TabbedPanel:
                    size_hint: (1,0.8)
                    id: floor2_center_tab_panel
                    do_default_tab: False
                    TabbedPanelItem:
                        id: floor2_center_1st_tab
                        text: "1st tab"
                        CustomLabel:
                            text: "1st tab"
                    TabbedPanelItem:
                        id: floor2_center_2nd_tab
                        text: "2nd tab"
                        CustomLabel:
                            text: "2nd tab"

        Screen:
            name: "2nd_floor_left_screen"
            GestureBox:
                on_bottom_to_top_line: manager.current = '1st_floor_center_screen';  manager.transition.direction = 'up'
                on_right_to_left_line: manager.current = '2nd_floor_center_screen'; manager.transition.direction = 'left'
                orientation: "vertical"

                CustomLabel:
					text: "2nd Floor Left"
					size_hint: (1,0.05)
                TabbedPanel:
                    size_hint: (1,0.8)
                    id: floor2_left_tab_panel
                    do_default_tab: False
                    TabbedPanelItem:
                        id: floor2_left_1st_tab
                        text: "1st tab"
                        CustomLabel:
                            text: "1st tab"
                    TabbedPanelItem:
                        id: floor2_left_2nd_tab
                        text: "2nd tab"
                        CustomLabel:
                            text: "2nd tab"

        Screen:
            name: "2nd_floor_right_screen"
            GestureBox:
                on_bottom_to_top_line: manager.current = '1st_floor_center_screen';  manager.transition.direction = 'up'
                on_left_to_right_line: manager.current = '2nd_floor_center_screen'; manager.transition.direction = 'right'
                orientation: "vertical"

                CustomLabel:
					text: "2nd Floor Right"
					size_hint: (1,0.05)
                TabbedPanel:
                    size_hint: (1,0.8)
                    id: floor2_right_tab_panel
                    do_default_tab: False
                    TabbedPanelItem:
                        id: floor2_right_1st_tab
                        text: "1st tab"
                        CustomLabel:
                            text: "1st tab"
                    TabbedPanelItem:
                        id: floor2_right_2nd_tab
                        text: "2nd tab"
                        CustomLabel:
                            text: "2nd tab"