<CustomLabel@Label>
	font_size: 28

<Plot>
	LineGraph:
		background_normal: ''
		background_color: [0,0,0,1]
		bg_color: ['Grey','000']
		orientation: 'vertical'
		padding: '5dp'
		spacing: '5dp'
		mode: "Line"
		id: line_graph

<GUILayout>
	ScreenManager:
		id: manager

		Screen:
			id: settings_screen
			name:"settings_screen"
			GestureBox:
				id: gesture_box_settings
				on_top_to_bottom_line: manager.current = 'first_floor_center_screen'; manager.transition.direction = 'down'
				orientation: "vertical"

				# Navigation
				GridLayout:
					cols: 2
					size: root.width, root.height * 0.15

					size_hint_y: None
					size_hint_x: None

					CustomLabel:
						text: "Settings"
						size_hint_y: None
						size_hint_x: None
						size: root.width * 0.8 , root.height * 0.15

					GridLayout:
						size: root.width * 0.2 , root.height * 0.15
						size_hint_y: None
						size_hint_x: None
						cols: 3
						rows: 3
						spacing: 10
						padding: 10
						row_force_default: True
						row_default_height: 30
						col_force_default: True
						col_default_width: 30

						Button:
							background_color: (2.09, 1.32, 0, 1)
							on_press:
								manager.transition.direction = 'down'
								manager.current = "second_floor_left_screen"

						Button:
							background_color: (2.09, 1.32, 0, 1)
							on_press:
								manager.transition.direction = 'down'
								manager.current = "second_floor_center_screen"

						Button:
							background_color: (2.09, 1.32, 0, 1)
							on_press:
								manager.transition.direction = 'down'
								manager.current = "second_floor_right_screen"

						Button:
							background_color: (2.09, 1.32, 0, 1)
							on_press:
								manager.transition.direction = 'down'
								manager.current = "first_floor_left_screen"

						Button:
							background_color: (2.09, 1.32, 0, 1)
							on_press:
								manager.transition.direction = 'down'
								manager.current = "first_floor_center_screen"

						Button:
							background_color: (2.09, 1.32, 0, 1)
							on_press:
								manager.transition.direction = 'down'
								manager.current = "first_floor_right_screen"

						Label:
						Button:
							background_color: (0, 1.32, 0, 1)
							on_press:
								manager.current = "settings_screen"

						Label:

				BoxLayout:
					GridLayout:
						cols: 4
						rows: 4
						spacing: 10
						padding: 10

						Label:
							text: "Temperature [in °C]"
						# 1st row
						AnchorLayout:
							anchor_x: 'center'
							Gauge:
								id: gauge_settings_temperature
								size_hint_y: 0.33
								value: root.hw_manager.dummy_sensor_temperature.value
								relative_path: './sensors/temperature_gauge.png'
						Label:
							text: "Temperature will be \n set to " + "{:.2f}".format(slider_settings_temperature_adjustment.value) + "°C"
						Slider:
							id: slider_settings_temperature_adjustment
							min: 10
							max: 40
							value: 20
							orientation: 'horizontal'
							on_value: root.hw_manager.manual_temperature_adjustment(self.value)

						# 2nd row
						Label:
							text: "Average brightness [in nm]"
						AnchorLayout:
							anchor_x: 'center'
							Gauge:
								id: gauge_settings_average_brightness
								size_hint_y: 0.33
								value: root.hw_manager.dummy_sensor_uv.value
								relative_path: './sensors/uv_gauge.png'
						Label:
							text: "Light control"
						Switch:
							on_active: root.hw_manager.enable_lights(self.active)

						# 3rd row
						Label:
							text: "Water level [in mm]"
						AnchorLayout:
							anchor_x: 'center'
							Gauge:
								id: gauge_settings_water_level
								size_hint_y: 0.33
								value: 50
						Label:
							text: "Automatic water filling"
						Switch:
							on_active: root.hw_manager.enable_automatic_water_filling(self.active)

						# 3rd row
						Label:
							text: ""
						Label:
							text: "Toggle Touch Gestures"
						Switch:
							active: True
							on_active:
							    gesture_box_settings.toggleGestures()
							    gesture_box_1st_floor_center.toggleGestures()
							    gesture_box_1st_floor_left.toggleGestures()
							    gesture_box_1st_floor_right.toggleGestures()
							    gesture_box_2nd_floor_left.toggleGestures()
							    gesture_box_2nd_floor_center.toggleGestures()
							    gesture_box_2nd_floor_right.toggleGestures()


		Screen:
			id: first_floor_center_screen
			name: "first_floor_center_screen"
			GestureBox:
				id: gesture_box_1st_floor_center
				on_top_to_bottom_line: manager.current = 'second_floor_center_screen';  manager.transition.direction = 'down'
				on_bottom_to_top_line: manager.current = 'settings_screen'; manager.transition.direction = 'up'
				on_left_to_right_line: manager.current = 'first_floor_left_screen'; manager.transition.direction = 'right'
				on_right_to_left_line: manager.current = 'first_floor_right_screen'; manager.transition.direction = 'left'
				orientation: "vertical"

				# Navigation
				GridLayout:
					cols: 2
					size: root.width, root.height * 0.15

					size_hint_y: None
					size_hint_x: None

					CustomLabel:
						text: "1st Floor Center"
						size_hint_y: None
						size_hint_x: None
						size: root.width * 0.8 , root.height * 0.15

					GridLayout:
						size: root.width * 0.2 , root.height * 0.15
						size_hint_y: None
						size_hint_x: None
						cols: 3
						rows: 3
						spacing: 10
						padding: 10
						row_force_default: True
						row_default_height: 30
						col_force_default: True
						col_default_width: 30

						Button:
							background_color: (2.09, 1.32, 0, 1)
							on_press:
								manager.transition.direction = 'down'
								manager.current = "second_floor_left_screen"

						Button:
							background_color: (2.09, 1.32, 0, 1)
							on_press:
								manager.transition.direction = 'down'
								manager.current = "second_floor_center_screen"

						Button:
							background_color: (2.09, 1.32, 0, 1)
							on_press:
								manager.transition.direction = 'down'
								manager.current = "second_floor_right_screen"

						Button:
							background_color: (2.09, 1.32, 0, 1)
							on_press:
								manager.transition.direction = 'right'
								manager.current = "first_floor_left_screen"

						Button:
							background_color: (0, 1.32, 0, 1)
							on_press:
								manager.current = "first_floor_center_screen"

						Button:
							background_color: (2.09, 1.32, 0, 1)
							on_press:
								manager.transition.direction = 'left'
								manager.current = "first_floor_right_screen"

						Label:
						Button:
							background_color: (2.09, 1.32, 0, 1)
							on_press:
								manager.transition.direction = 'up'
								manager.current = "settings_screen"

						Label:
				TabbedPanel:
					id: floor1_center_tab_panel
					do_default_tab: False
					size_hint: (1,0.8)

					TabbedPanelItem:
						id: floor1_center_overview_tab
						text: "Overview"
						background_color: (2.09, 1.32, 0, 1) #orange tab

						GridLayout:
							cols: 4
							rows: 3
							spacing: 10
							padding: 10

							CustomLabel:
								text: "Temperature \n [in °C]"
							AnchorLayout:
								anchor_x: 'center'
								Gauge:
									id: gauge_1st_center_overview_temperature
									size_hint_y: 0.33
									value: root.hw_manager.dummy_sensor_temperature.value
									relative_path: './sensors/temperature_gauge.png'

							CustomLabel:
								text: "Humidity \n [in %]"
							AnchorLayout:
								anchor_x: 'center'
								Gauge:
									id: gauge_1st_center_overview_humidity
									size_hint_y: 0.33
									value: root.hw_manager.dummy_sensor_humidity.value

							CustomLabel:
								text: "Air Pressure \n [in hPa]"
							AnchorLayout:
								anchor_x: 'center'
								Gauge:
									id: gauge_1st_center_overview_air_pressure
									size_hint_y: 0.33
									value: root.hw_manager.dummy_sensor_air_pressure.value
									relative_path: './sensors/air_pressure_gauge.png'

							CustomLabel:
								text: "UV \n [in nm]"
							AnchorLayout:
								anchor_x: 'center'
								Gauge:
									id: gauge_1st_center_overview_uv
									size_hint_y: 0.33
									value: root.hw_manager.dummy_sensor_uv.value
									relative_path: './sensors/uv_gauge.png'

							CustomLabel:
								text: "Soil Moisture \n [in %]"
							AnchorLayout:
								anchor_x: 'center'
								Gauge:
									id: gauge_1st_center_overview_soil_moisture
									size_hint_y: 0.33
									value: root.hw_manager.dummy_sensor_soil_moisture.value

					TabbedPanelItem:
						id: floor1_center_temperature_tab
						text: "Temperature"

						GridLayout:
							rows: 2
							GridLayout:
								cols: 2
								size_hint_y: None
								height: 90

								AnchorLayout:
									anchor_x: 'left'
									CustomLabel:
										text: "Temperature Value [in °C]"
										size_hint_x: None
										width: 500

								AnchorLayout:
									anchor_x: 'right'
									Gauge:
										id: gauge_1st_center_tab_temperature
										size_hint_x: None
										size_hint_y: 0.5
										width: 300
										value: root.hw_manager.dummy_sensor_temperature.value
										relative_path: './sensors/temperature_gauge.png'

							GridLayout:
								cols: 2
								GridLayout:
									rows: 2
									width: 100
									size_hint_x: None
									Button:
										text: "show \n less"
										on_press: plot_1st_center_tab_temperature.showLess()

									Button:
										text: "show \n more"
										on_press: plot_1st_center_tab_temperature.showMore()

								BoxLayout:
									Plot:
										id: plot_1st_center_tab_temperature
										yMin: -10
										yMax: 40
										yStep: 10
										value: root.hw_manager.dummy_sensor_temperature.value
										name: "first_floor_center_screen"
										current: manager.current

					TabbedPanelItem:
						id: floor1_center_humidity_tab
						text: "Humidity"

						GridLayout:
							rows: 2
							GridLayout:
								cols: 2
								size_hint_y: None
								height: 90

								AnchorLayout:
									anchor_x: 'left'
									CustomLabel:
										text: "Humidity Value [in %]"
										size_hint_x: None
										width : 500

								AnchorLayout:
									anchor_x: 'right'
									Gauge:
										id: gauge_1st_center_tab_humidity
										size_hint_x: None
										size_hint_y: 0.5
										width: 300
										value: root.hw_manager.dummy_sensor_humidity.value

							GridLayout:
								cols: 2
								GridLayout:
									rows: 2
									width: 100
									size_hint_x: None
									Button:
										text: "show \n less"
										on_press: plot_1st_center_tab_humidity.showLess()

									Button:
										text: "show \n more"
										on_press: plot_1st_center_tab_humidity.showMore()

								BoxLayout:
									Plot:
										id: plot_1st_center_tab_humidity
										yMin: 0
										yMax: 100
										yStep: 10
										value: root.hw_manager.dummy_sensor_humidity.value
										name: "first_floor_center_screen"
										current: manager.current

					TabbedPanelItem:
						id: floor1_center_air_pressure_tab
						text: "Air Pressure"

						GridLayout:
							rows: 2
							GridLayout:
								cols: 2
								size_hint_y: None
								height: 90

								AnchorLayout:
									anchor_x: 'left'
									CustomLabel:
										text: "Air Pressure Value [in hPa]"
										size_hint_x: None
										width : 500

								AnchorLayout:
									anchor_x: 'right'
									Gauge:
										id: gauge_1st_center_tab_air_pressure
										size_hint_x: None
										size_hint_y: 0.5
										width: 300
										value: root.hw_manager.dummy_sensor_air_pressure.value
										relative_path: './sensors/air_pressure_gauge.png'

							GridLayout:
								cols: 2
								GridLayout:
									rows: 2
									width: 100
									size_hint_x: None
									Button:
										text: "show \n less"
										on_press: plot_1st_center_tab_air_pressure.showLess()

									Button:
										text: "show \n more"
										on_press: plot_1st_center_tab_air_pressure.showMore()

								BoxLayout:
									Plot:
										id: plot_1st_center_tab_air_pressure
										yMin: 950
										yMax: 1050
										yStep: 10
										value: root.hw_manager.dummy_sensor_air_pressure.value
										name: "first_floor_center_screen"
										current: manager.current

					TabbedPanelItem:
						id: floor1_center_uv_tab
						text: "UV"

						GridLayout:
							rows: 2
							GridLayout:
								cols: 2
								size_hint_y: None
								height: 90

								AnchorLayout:
									anchor_x: 'left'
									CustomLabel:
										text: "UV Value [in nm]"
										size_hint_x: None
										width : 500

								AnchorLayout:
									anchor_x: 'right'
									Gauge:
										id: gauge_1st_center_tab_uv
										size_hint_x: None
										size_hint_y: 0.5
										width: 300
										value: root.hw_manager.dummy_sensor_uv.value
										relative_path: './sensors/uv_gauge.png'

							GridLayout:
								cols: 2
								GridLayout:
									rows: 2
									width: 100
									size_hint_x: None
									Button:
										text: "show \n less"
										on_press: plot_1st_center_tab_uv.showLess()

									Button:
										text: "show \n more"
										on_press: plot_1st_center_tab_uv.showMore()

								BoxLayout:
									Plot:
										id: plot_1st_center_tab_uv
										yMin: 100
										yMax: 400
										yStep: 50
										value: root.hw_manager.dummy_sensor_uv.value
										name: "first_floor_center_screen"
										current: manager.current

					TabbedPanelItem:
						id: floor1_center_soil_moisture_tab
						text: "Soil Moisture"

						GridLayout:
							rows: 2
							GridLayout:
								cols: 2
								size_hint_y: None
								height: 90

								AnchorLayout:
									anchor_x: 'left'
									CustomLabel:
										text: "Soil Moisture Value [in %]"
										size_hint_x: None
										width : 500

								AnchorLayout:
									anchor_x: 'right'
									Gauge:
										id: gauge_1st_center_tab_soil_moisture
										size_hint_x: None
										size_hint_y: 0.5
										width: 300
										value: root.hw_manager.dummy_sensor_soil_moisture.value

							GridLayout:
								cols: 2
								GridLayout:
									rows: 2
									width: 100
									size_hint_x: None
									Button:
										text: "show \n less"
										on_press: plot_1st_center_tab_soil_moisture.showLess()

									Button:
										text: "show \n more"
										on_press: plot_1st_center_tab_soil_moisture.showMore()

								BoxLayout:
									Plot:
										id: plot_1st_center_tab_soil_moisture
										yMin: 0
										yMax: 100
										yStep: 10
										value: root.hw_manager.dummy_sensor_soil_moisture.value
										name: "first_floor_center_screen"
										current: manager.current

		Screen:
			id: first_floor_left_screen
			name: "first_floor_left_screen"
			GestureBox:
				id: gesture_box_1st_floor_left
				on_bottom_to_top_line: manager.current = 'settings_screen';  manager.transition.direction = 'up'
				on_right_to_left_line: manager.current = 'first_floor_center_screen';  manager.transition.direction = 'left'
				on_top_to_bottom_line: manager.current = 'second_floor_center_screen';  manager.transition.direction = 'down'
				orientation: "vertical"

				# Navigation
				GridLayout:
					cols: 2
					size: root.width, root.height * 0.15

					size_hint_y: None
					size_hint_x: None

					CustomLabel:
						text: "1st Floor Left"
						size_hint_y: None
						size_hint_x: None
						size: root.width * 0.8 , root.height * 0.15

					GridLayout:
						size: root.width * 0.2 , root.height * 0.15
						size_hint_y: None
						size_hint_x: None
						cols: 3
						rows: 3
						spacing: 10
						padding: 10
						row_force_default: True
						row_default_height: 30
						col_force_default: True
						col_default_width: 30

						Button:
							background_color: (2.09, 1.32, 0, 1)
							on_press:
								manager.transition.direction = 'down'
								manager.current = "second_floor_left_screen"

						Button:
							background_color: (2.09, 1.32, 0, 1)
							on_press:
								manager.transition.direction = 'down'
								manager.current = "second_floor_center_screen"

						Button:
							background_color: (2.09, 1.32, 0, 1)
							on_press:
								manager.transition.direction = 'down'
								manager.current = "second_floor_right_screen"

						Button:
							background_color: (0, 1.32, 0, 1)
							on_press: manager.current = "first_floor_left_screen"

						Button:
							background_color: (2.09, 1.32, 0, 1)
							on_press:
								manager.transition.direction = 'left'
								manager.current = "first_floor_center_screen"

						Button:
							background_color: (2.09, 1.32, 0, 1)
							on_press:
								manager.transition.direction = 'left'
								manager.current = "first_floor_right_screen"

						Label:
						Button:
							background_color: (2.09, 1.32, 0, 1)
							on_press:
								manager.transition.direction = 'up'
								manager.current = "settings_screen"

						Label:

				TabbedPanel:
					size_hint: (1,0.8)
					id: floor1_left_tab_panel
					do_default_tab: False
					TabbedPanelItem:
						id: floor1_left_1st_tab
						text: "1st tab"
						CustomLabel:
							text: "1st tab"
					TabbedPanelItem:
						id: floor1_left_2nd_tab
						text: "2nd tab"
						CustomLabel:
							text: "2nd tab"

		Screen:
			id: first_floor_right_screen
			name: "first_floor_right_screen"
			GestureBox:
				id: gesture_box_1st_floor_right
				on_bottom_to_top_line: manager.current = 'settings_screen';  manager.transition.direction = 'up'
				on_left_to_right_line: manager.current = 'first_floor_center_screen';  manager.transition.direction = 'right'
				on_top_to_bottom_line: manager.current = 'second_floor_center_screen';  manager.transition.direction = 'down'
				orientation: "vertical"

				# Navigation
				GridLayout:
					cols: 2
					size: root.width, root.height * 0.15

					size_hint_y: None
					size_hint_x: None

					CustomLabel:
						text: "1st Floor Right"
						size_hint_y: None
						size_hint_x: None
						size: root.width * 0.8 , root.height * 0.15

					GridLayout:
						size: root.width * 0.2 , root.height * 0.15
						size_hint_y: None
						size_hint_x: None
						cols: 3
						rows: 3
						spacing: 10
						padding: 10
						row_force_default: True
						row_default_height: 30
						col_force_default: True
						col_default_width: 30

						Button:
							background_color: (2.09, 1.32, 0, 1)
							on_press:
								manager.transition.direction = 'down'
								manager.current = "second_floor_left_screen"

						Button:
							background_color: (2.09, 1.32, 0, 1)
							on_press:
								manager.transition.direction = 'down'
								manager.current = "second_floor_center_screen"

						Button:
							background_color: (2.09, 1.32, 0, 1)
							on_press:
								manager.transition.direction = 'down'
								manager.current = "second_floor_right_screen"

						Button:
							background_color: (2.09, 1.32, 0, 1)
							on_press:
								manager.transition.direction = 'right'
								manager.current = "first_floor_left_screen"

						Button:
							background_color: (2.09, 1.32, 0, 1)
							on_press:
								manager.transition.direction = 'right'
								manager.current = "first_floor_center_screen"

						Button:
							background_color: (0, 1.32, 0, 1)
							on_press:
								manager.current = "first_floor_right_screen"

						Label:
						Button:
							background_color: (2.09, 1.32, 0, 1)
							on_press:
								manager.transition.direction = 'up'
								manager.current = "settings_screen"

						Label:

				TabbedPanel:
					size_hint: (1,0.8)
					id: floor1_right_tab_panel
					do_default_tab: False
					TabbedPanelItem:
						id: floor1_right_1st_tab
						text: "1st tab"
						CustomLabel:
							text: "1st tab"
					TabbedPanelItem:
						id: floor1_right_2nd_tab
						text: "2nd tab"
						CustomLabel:
							text: "2nd tab"

		Screen:
			id: second_floor_center_screen
			name: "second_floor_center_screen"
			GestureBox:
				id: gesture_box_2nd_floor_center
				on_bottom_to_top_line: manager.current = 'first_floor_center_screen';  manager.transition.direction = 'up'
				on_left_to_right_line: manager.current = 'second_floor_left_screen'; manager.transition.direction = 'right'
				on_right_to_left_line: manager.current = 'second_floor_right_screen'; manager.transition.direction = 'left'
				orientation: "vertical"

				# Navigation
				GridLayout:
					cols: 2
					size: root.width, root.height * 0.15

					size_hint_y: None
					size_hint_x: None

					CustomLabel:
						text: "2nd Floor Center"
						size_hint_y: None
						size_hint_x: None
						size: root.width * 0.8 , root.height * 0.15

					GridLayout:
						size: root.width * 0.2 , root.height * 0.15
						size_hint_y: None
						size_hint_x: None
						cols: 3
						rows: 3
						spacing: 10
						padding: 10
						row_force_default: True
						row_default_height: 30
						col_force_default: True
						col_default_width: 30

						Button:
							background_color: (2.09, 1.32, 0, 1)
							on_press:
								manager.transition.direction = 'right'
								manager.current = "second_floor_left_screen"

						Button:
							background_color: (0, 1.32, 0, 1)
							on_press:
								manager.current = "second_floor_center_screen"

						Button:
							background_color: (2.09, 1.32, 0, 1)
							on_press:
								manager.transition.direction = 'left'
								manager.current = "second_floor_right_screen"

						Button:
							background_color: (2.09, 1.32, 0, 1)
							on_press:
								manager.transition.direction = 'up'
								manager.current = "first_floor_left_screen"

						Button:
							background_color: (2.09, 1.32, 0, 1)
							on_press:
								manager.transition.direction = 'up'
								manager.current = "first_floor_center_screen"

						Button:
							background_color: (2.09, 1.32, 0, 1)
							on_press:
								manager.transition.direction = 'up'
								manager.current = "first_floor_right_screen"

						Label:
						Button:
							background_color: (2.09, 1.32, 0, 1)
							on_press:
								manager.transition.direction = 'up'
								manager.current = "settings_screen"

						Label:

				TabbedPanel:
					size_hint: (1,0.8)
					id: floor2_center_tab_panel
					do_default_tab: False
					TabbedPanelItem:
						id: floor2_center_1st_tab
						text: "1st tab"
						CustomLabel:
							text: "1st tab"
					TabbedPanelItem:
						id: floor2_center_2nd_tab
						text: "2nd tab"
						CustomLabel:
							text: "2nd tab"

		Screen:
			id: second_floor_left_screen
			name: "second_floor_left_screen"
			GestureBox:
				id: gesture_box_2nd_floor_left
				on_bottom_to_top_line: manager.current = 'first_floor_center_screen';  manager.transition.direction = 'up'
				on_right_to_left_line: manager.current = 'second_floor_center_screen'; manager.transition.direction = 'left'
				orientation: "vertical"

				# Navigation
				GridLayout:
					cols: 2
					size: root.width, root.height * 0.15

					size_hint_y: None
					size_hint_x: None

					CustomLabel:
						text: "2nd Floor Left"
						size_hint_y: None
						size_hint_x: None
						size: root.width * 0.8 , root.height * 0.15

					GridLayout:
						size: root.width * 0.2 , root.height * 0.15
						size_hint_y: None
						size_hint_x: None
						cols: 3
						rows: 3
						spacing: 10
						padding: 10
						row_force_default: True
						row_default_height: 30
						col_force_default: True
						col_default_width: 30

						Button:
							background_color: (0, 1.32, 0, 1)
							on_press:
								manager.current = "second_floor_left_screen"

						Button:
							background_color: (2.09, 1.32, 0, 1)
							on_press:
								manager.transition.direction = 'left'
								manager.current = "second_floor_center_screen"

						Button:
							background_color: (2.09, 1.32, 0, 1)
							on_press:
								manager.transition.direction = 'left'
								manager.current = "second_floor_right_screen"

						Button:
							background_color: (2.09, 1.32, 0, 1)
							on_press:
								manager.transition.direction = 'up'
								manager.current = "first_floor_left_screen"

						Button:
							background_color: (2.09, 1.32, 0, 1)
							on_press:
								manager.transition.direction = 'up'
								manager.current = "first_floor_center_screen"

						Button:
							background_color: (2.09, 1.32, 0, 1)
							on_press:
								manager.transition.direction = 'up'
								manager.current = "first_floor_right_screen"

						Label:
						Button:
							background_color: (2.09, 1.32, 0, 1)
							on_press:
								manager.transition.direction = 'up'
								manager.current = "settings_screen"

						Label:
				TabbedPanel:
					size_hint: (1,0.8)
					id: floor2_left_tab_panel
					do_default_tab: False
					TabbedPanelItem:
						id: floor2_left_1st_tab
						text: "1st tab"
						CustomLabel:
							text: "1st tab"
					TabbedPanelItem:
						id: floor2_left_2nd_tab
						text: "2nd tab"
						CustomLabel:
							text: "2nd tab"

		Screen:
			id: second_floor_right_screen
			name: "second_floor_right_screen"
			GestureBox:
				id: gesture_box_2nd_floor_right
				on_bottom_to_top_line: manager.current = 'first_floor_center_screen';  manager.transition.direction = 'up'
				on_left_to_right_line: manager.current = 'second_floor_center_screen'; manager.transition.direction = 'right'
				orientation: "vertical"

				# Navigation
				GridLayout:
					cols: 2
					size: root.width, root.height * 0.15

					size_hint_y: None
					size_hint_x: None

					CustomLabel:
						text: "2nd Floor Right"
						size_hint_y: None
						size_hint_x: None
						size: root.width * 0.8 , root.height * 0.15

					GridLayout:
						size: root.width * 0.2 , root.height * 0.15
						size_hint_y: None
						size_hint_x: None
						cols: 3
						rows: 3
						spacing: 10
						padding: 10
						row_force_default: True
						row_default_height: 30
						col_force_default: True
						col_default_width: 30

						Button:
							background_color: (2.09, 1.32, 0, 1)
							on_press:
								manager.transition.direction = 'right'
								manager.current = "second_floor_left_screen"

						Button:
							background_color: (2.09, 1.32, 0, 1)
							on_press:
								manager.transition.direction = 'right'
								manager.current = "second_floor_center_screen"

						Button:
							background_color: (0, 1.32, 0, 1)
							on_press:
								manager.current = "second_floor_right_screen"

						Button:
							background_color: (2.09, 1.32, 0, 1)
							on_press:
								manager.transition.direction = 'up'
								manager.current = "first_floor_left_screen"

						Button:
							background_color: (2.09, 1.32, 0, 1)
							on_press:
								manager.transition.direction = 'up'
								manager.current = "first_floor_center_screen"

						Button:
							background_color: (2.09, 1.32, 0, 1)
							on_press:
								manager.transition.direction = 'up'
								manager.current = "first_floor_right_screen"

						Label:
						Button:
							background_color: (2.09, 1.32, 0, 1)
							on_press:
								manager.transition.direction = 'up'
								manager.current = "settings_screen"

						Label:

				TabbedPanel:
					size_hint: (1,0.8)
					id: floor2_right_tab_panel
					do_default_tab: False
					TabbedPanelItem:
						id: floor2_right_1st_tab
						text: "1st tab"
						CustomLabel:
							text: "1st tab"
					TabbedPanelItem:
						id: floor2_right_2nd_tab
						text: "2nd tab"
						CustomLabel:
							text: "2nd tab"

[Autoblabla@Base1]


