<CustomLabel@Label>
	font_size: 28

<Plot>
	LineGraph:
		background_normal: ''
		background_color: [0,0,0,1]
		bg_color: ['Grey','000']
		orientation: 'vertical'
		padding: '5dp'
		spacing: '5dp'
		mode: "Line"
		id: line_graph

<GUILayout>
    ScreenManager:
        id: manager

        Screen:
            id: settings_screen
            name:"settings_screen"
            GestureBox:
                on_top_to_bottom_line: manager.current = 'first_floor_center_screen'; manager.transition.direction = 'down'
                orientation: "vertical"
				# Navigation
                GridLayout:
                    cols: 2
                    size: root.width, root.height * 0.15
                    size_hint_y: None
                    size_hint_x: None
					CustomLabel:
                        text: "Settings"
                        size_hint_y: None
                        size_hint_x: None
                        size: root.width * 0.8 , root.height * 0.15
					GridLayout:
                        size: root.width * 0.2 , root.height * 0.15
                        size_hint_y: None
                        size_hint_x: None
                        cols: 3
                        rows: 3
                        spacing: 10
                        padding: 10
                        row_force_default: True
                        row_default_height: 30
                        col_force_default: True
                        col_default_width: 30

                        Button:
                            background_color: (2.09, 1.32, 0, 1)
							on_press:
                                manager.transition.direction = 'down'
                                manager.current = "second_floor_left_screen"
						Button:
