#:directive/to/import

Root:
    canvas:
        Color:
            rgb: 1, 1, 1
        Rectangle:
            size: (32, 32)
    canvas.before:
        Color:
            rgb: 1, 1, 1
        Rectangle:
            size: (32, 32)
    canvas.after:
        Color:
            rgb: 1, 1, 1
        Rectangle:
            size: (32, 32)

[IconItem@BoxLayout]:
    Image:
        source: ctx.image
    Label:
        text: ctx.title
